name: Deploy Flask Docker App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: Zip the Flask app
        run: |
          cd app
          zip -r ../app.zip .

      - name: Copy app.zip to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem app.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Clean old files
            rm -rf app && mkdir app
            mv app.zip app/
            cd app
            unzip app.zip
            rm app.zip

            # Build and run Docker container
            sudo docker rm -f flaskapp || true
            sudo docker build -t flaskapp .
            sudo docker run -d -p 80:80 --name flaskapp flaskapp
          EOF
