name: Deploy Flask Docker App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Remove old container if running
            docker rm -f flaskapp || true

            # Navigate or clone repo on EC2
            if [ ! -d DevOps-demo-19-07 ]; then
              git clone https://github.com/YOUR-USERNAME/DevOps-demo-19-07.git
            else
              cd DevOps-demo-19-07 && git pull
            fi
            cd DevOps-demo-19-07/app

            # Build and run Docker container
            docker build -t flaskapp .
            docker run -d -p 80:80 --name flaskapp flaskapp
          EOF
