name: EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      run: terraform init && terraform apply -auto-approve

    - name: Save Private Key
      run: |
        terraform output -raw private_key_pem > private_key.pem
        chmod 600 private_key.pem

    - name: Upload Key Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ec2-private-key
        path: private_key.pem

    - name: Set Public IP
      run: echo "IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: SCP app.zip
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem app.zip ec2-user@$IP:/home/ec2-user/
